cmake_minimum_required(VERSION 3.25)
project(SdizoProjekt2)

set(CMAKE_CXX_STANDARD 17)

add_executable(SdizoProjekt2 main.cpp FileReader.cpp FileReader.h MatrixGraph.cpp MatrixGraph.h NListGraph.cpp NListGraph.h ArrayList.cpp ArrayList.h DList.cpp DList.h Heap.cpp Heap.h LinkedList.cpp LinkedList.h NList.cpp NList.h TabUtils.cpp TabUtils.h KruskalHelper.cpp KruskalHelper.h Graph.h)
